export interface MenuItem {
  id: string;
  name: string;
  price: string;
  unit?: string;
  badge?: string;
  image: string;
  description?: string;
  category: string;
}

const U = (id: string) =>
  `https://images.unsplash.com/${id}?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=600`;

export const categories = [
  { id: "entrees", label: "Entrées & Nems" },
  { id: "vapeur", label: "Bouchées Vapeur" },
  { id: "salades", label: "Salades & Sushi" },
  { id: "plats", label: "Plats Chauds" },
  { id: "accompagnements", label: "Accompagnements" },
  { id: "desserts", label: "Desserts" },
];

export const menuItems: MenuItem[] = [
  // ── ENTRÉES & NEMS ──────────────────────────────────────────────────────
  {
    id: "nem-porc",
    name: "Nem au Porc",
    price: "0,90€",
    unit: "/ pièce",
    image: U("photo-1776178393305-be4c1097fae5"),
    description: "Nem croustillant au porc et légumes, frit à la perfection.",
    category: "entrees",
  },
  {
    id: "nem-poulet-90",
    name: "Nem au Poulet",
    price: "0,90€",
    unit: "/ pièce",
    image: U("photo-1767469576689-968335dbabb5"),
    description: "Nem au poulet doré et croustillant, farce parfumée aux épices.",
    category: "entrees",
  },
  {
    id: "nem-poulet-95",
    name: "Nem au Poulet (grand)",
    price: "0,95€",
    unit: "/ pièce",
    image: U("photo-1679310290259-78d9eaa32700"),
    description: "Grand nem au poulet extra-croustillant, portion généreuse.",
    category: "entrees",
  },
  {
    id: "nem-crevettes",
    name: "Nem aux Crevettes",
    price: "0,95€",
    unit: "/ pièce",
    image: U("photo-1776178393305-be4c1097fae5"),
    description: "Nem aux crevettes fraîches, enveloppé dans une fine feuille dorée.",
    category: "entrees",
  },
  {
    id: "ravioli-frit-crevettes",
    name: "Ravioli Frit aux Crevettes",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1769610712810-ec91babfccd3"),
    description: "Ravioli frit croustillant farci aux crevettes.",
    category: "entrees",
  },
  {
    id: "ravioli-frit-porc",
    name: "Ravioli Frit au Porc",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1769610712810-ec91babfccd3"),
    description: "Ravioli frit au porc assaisonné, bien doré et fondant à l'intérieur.",
    category: "entrees",
  },
  {
    id: "brochette-poulet-citronnelle",
    name: "Brochette de Poulet Citronnelle",
    price: "2,00€",
    unit: "/ pièce",
    image: U("photo-1696385793103-71f51f6fd3b7"),
    description: "Tendre poulet mariné à la citronnelle, grillé sur brochette.",
    category: "entrees",
  },
  {
    id: "tempura-crevette",
    name: "Tempura Crevette",
    price: "1,20€",
    unit: "/ pièce",
    image: U("photo-1579887829114-282b4fa31072"),
    description: "Crevette enrobée d'une pâte tempura légère et aérienne, frite à la japonaise.",
    category: "entrees",
  },
  {
    id: "samousa-boeuf",
    name: "Samousa au Bœuf",
    price: "0,90€",
    unit: "/ pièce",
    image: U("photo-1601050690117-94f5f6fa8bd7"),
    description: "Triangle feuilleté croustillant garni de bœuf épicé et d'oignons.",
    category: "entrees",
  },
  {
    id: "poulet-frit",
    name: "Poulet Frit",
    price: "4,50€",
    unit: "/ 5 pièces",
    image: U("photo-1762941904142-9d91ca413e66"),
    description: "5 morceaux de poulet frit croustillant, tendres à cœur.",
    category: "entrees",
  },
  {
    id: "brochette-boeuf-fromage",
    name: "Brochette de Bœuf Fromage",
    price: "1,80€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1498530875991-2806ee9dd6d1"),
    description: "Bœuf grillé en brochette avec un cœur fondant de fromage.",
    category: "entrees",
  },
  {
    id: "rouleau-printemps",
    name: "Rouleau de Printemps",
    price: "2,20€",
    unit: "/ pièce",
    image: U("photo-1618406854423-ef169758d6a6"),
    description: "Rouleau frais de riz garni de légumes croquants, herbes et vermicelles.",
    category: "entrees",
  },

  // ── BOUCHÉES VAPEUR ─────────────────────────────────────────────────────
  {
    id: "gyoza",
    name: "Gyoza (Ravioli au Poulet)",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1638502338747-f7f368214cce"),
    description: "Gyoza poêlé au poulet haché, légèrement grillé en dessous et vapeur au-dessus.",
    category: "vapeur",
  },
  {
    id: "bouchee-porc",
    name: "Bouchée de Porc",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1638502521795-89107ac5e246"),
    description: "Délicate bouchée vapeur farcie au porc parfumé.",
    category: "vapeur",
  },
  {
    id: "bouchee-crevettes",
    name: "Bouchée aux Crevettes",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1563245372-f21724e3856d"),
    description: "Bouchée moelleuse aux crevettes fraîches, pâte vapeur fine et translucide.",
    category: "vapeur",
  },
  {
    id: "ravioli-crevettes-vapeur",
    name: "Ravioli aux Crevettes",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1563245372-f21724e3856d"),
    description: "Ravioli vapeur aux crevettes, enveloppé dans une fine pâte translucide.",
    category: "vapeur",
  },
  {
    id: "ravioli-st-jacques",
    name: "Ravioli Saint-Jacques",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1608651273724-cfee1bd12cf6"),
    description: "Ravioli vapeur à la noix de Saint-Jacques, finesse et goût marin délicat.",
    category: "vapeur",
  },
  {
    id: "ravioli-poulet-vapeur",
    name: "Ravioli au Poulet",
    price: "0,90€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1638502338747-f7f368214cce"),
    description: "Ravioli vapeur tendre au poulet assaisonné, doux et parfumé.",
    category: "vapeur",
  },

  // ── SALADES & SUSHI ─────────────────────────────────────────────────────
  {
    id: "salade-algues",
    name: "Salade d'Algues",
    price: "1,90€",
    unit: "/ 100g",
    image: U("photo-1772198537754-6ad327158f96"),
    description: "Salade d'algues marines assaisonnées à la japonaise, fraîche et iodée.",
    category: "salades",
  },
  {
    id: "salade-choux",
    name: "Salade de Choux",
    price: "1,60€",
    unit: "/ 100g",
    image: U("photo-1630409350018-0e06ea178b92"),
    description: "Salade de choux croquante assaisonnée à la façon asiatique.",
    category: "salades",
  },
  {
    id: "sushi-maki",
    name: "Sushi & Maki",
    price: "5,50€ / 12€",
    unit: "petite / grande barquette",
    image: U("photo-1611143669185-af224c5e3252"),
    description: "Assortiment de sushis et makis frais. Petite barquette 5,50€ — Grande barquette 12€.",
    category: "salades",
  },

  // ── PLATS CHAUDS ────────────────────────────────────────────────────────
  {
    id: "boulette-poulet",
    name: "Boulette de Poulet",
    price: "2,50€",
    unit: "/ 100g",
    image: U("photo-1706740006781-3ca0149307e5"),
    description: "Boulettes de poulet mijotées, moelleuses et savoureuses.",
    category: "plats",
  },
  {
    id: "poulet-aigre-douce",
    name: "Poulet à la Sauce Aigre-Douce",
    price: "2,40€",
    unit: "/ 100g",
    image: U("photo-1623689048105-a17b1e1936b8"),
    description: "Poulet laqué à la sauce aigre-douce, équilibre parfait sucré-acidulé.",
    category: "plats",
  },
  {
    id: "poulet-croustillant",
    name: "Poulet Croustillant",
    price: "2,40€",
    unit: "/ 100g",
    image: U("photo-1762941904142-9d91ca413e66"),
    description: "Poulet pané croustillant à l'extérieur, fondant et juteux à l'intérieur.",
    category: "plats",
  },
  {
    id: "canard-laque",
    name: "Canard Laqué",
    price: "2,80€",
    unit: "/ 100g",
    image: U("photo-1765441012353-10fb4701a276"),
    description: "Canard laqué traditionnel, peau croustillante et chair fondante caramélisée.",
    category: "plats",
  },
  {
    id: "brochette-poulet-caramel",
    name: "Brochette de Poulet Caramel",
    price: "1,20€",
    unit: "/ pièce",
    badge: "5 + 1 offert",
    image: U("photo-1645371958635-88dd6c8e1be7"),
    description: "Brochette de poulet glacée au caramel doré, tendre et délicieusement sucrée.",
    category: "plats",
  },
  {
    id: "poulet-thai",
    name: "Poulet Thaï",
    price: "2,80€",
    unit: "/ 100g",
    image: U("photo-1621515554656-3da68ba128b1"),
    description: "Poulet sauté à la sauce thaï, basilic et piments, légèrement épicé.",
    category: "plats",
  },
  {
    id: "poulet-gingembre",
    name: "Poulet Gingembre",
    price: "2,80€",
    unit: "/ 100g",
    image: U("photo-1604908176997-125f25cc6f3d"),
    description: "Poulet sauté au gingembre frais et aux oignons, parfumé et tonique.",
    category: "plats",
  },
  {
    id: "porc-caramel",
    name: "Porc Caramel",
    price: "2,40€",
    unit: "/ 100g",
    image: U("photo-1593030668930-8130abedd2b0"),
    description: "Porc mijoté dans un caramel ambré, fondant et irrésistiblement sucré-salé.",
    category: "plats",
  },
  {
    id: "poulet-caramel",
    name: "Poulet Caramel",
    price: "2,40€",
    unit: "/ 100g",
    image: U("photo-1602253057119-44d745d9b860"),
    description: "Poulet glacé au caramel, laqué et fondant avec une belle couleur dorée.",
    category: "plats",
  },
  {
    id: "boeuf-sauce-piquante",
    name: "Bœuf à la Sauce Piquante",
    price: "2,60€",
    unit: "/ 100g",
    image: U("photo-1604908177453-7462950a6a3b"),
    description: "Bœuf tendre sauté dans une sauce relevée, légumes croquants.",
    category: "plats",
  },
  {
    id: "boeuf-oignons",
    name: "Bœuf aux Oignons",
    price: "2,60€",
    unit: "/ 100g",
    image: U("photo-1760504526069-ff0f8bf6e4ca"),
    description: "Bœuf sauté aux oignons confits et poivrons, parfumé et savoureux.",
    category: "plats",
  },
  {
    id: "crevettes-sauce-piquante",
    name: "Crevettes à la Sauce Piquante",
    price: "3,50€",
    unit: "/ 100g",
    image: U("photo-1766566959672-257837bc6c76"),
    description: "Crevettes sautées dans une sauce épicée au piment, relevée et parfumée.",
    category: "plats",
  },
  {
    id: "gambas-sel-poivre",
    name: "Gambas Sel et Poivre",
    price: "4,80€",
    unit: "/ 100g",
    image: U("photo-1627703378753-a7a5d0a87ee6"),
    description: "Gambas sautées au sel et au poivre du Sichuan, croustillantes et parfumées.",
    category: "plats",
  },

  // ── ACCOMPAGNEMENTS ─────────────────────────────────────────────────────
  {
    id: "riz-thai",
    name: "Riz Thaï",
    price: "1,50€",
    unit: "/ 100g",
    image: U("photo-1664717698774-84f62382613b"),
    description: "Riz thaï jasmin cuit à la vapeur, doux et légèrement parfumé.",
    category: "accompagnements",
  },
  {
    id: "riz-cantonnais",
    name: "Riz Cantonnais",
    price: "1,50€",
    unit: "/ 100g",
    image: U("photo-1603133872878-684f208fb84b"),
    description: "Riz sauté aux œufs, petits pois, jambon et légumes — recette classique cantonaise.",
    category: "accompagnements",
  },
  {
    id: "nouilles-legumes",
    name: "Nouilles Sautées aux Légumes",
    price: "1,50€",
    unit: "/ 100g",
    image: U("photo-1585032226651-759b368d7246"),
    description: "Nouilles sautées au wok avec des légumes croquants et sauce soja.",
    category: "accompagnements",
  },

  // ── DESSERTS ─────────────────────────────────────────────────────────────
  {
    id: "perle-coco",
    name: "Perle de Coco",
    price: "1,00€",
    unit: "/ pièce",
    image: U("photo-1676364000560-eefe24b03c45"),
    description: "Douceur à base de coco, délicate et fondante en bouche.",
    category: "desserts",
  },
  {
    id: "nougat-gingembre",
    name: "Nougat Chinois ou Gingembre Confit",
    price: "3,50€",
    unit: "/ pièce",
    image: U("photo-1646552808104-e89cffc46d2f"),
    description: "Nougat traditionnel aux graines de sésame ou gingembre confit au sirop.",
    category: "desserts",
  },
];
